openapi: 3.1.0
info:
  title: Chat App API
  version: 1.0.0

paths:
  /signup:
    post:
      summary: ユーザー登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: 登録成功
        '400':
          description: 無効な入力
        '500':
          description: サーバーエラー

components:
  schemas:
    SignupRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
